### ISSUE TITLE
Is there a way to restore http://192.168.4.1/jpg_stream ?

### ISSUE THREAD

**Issue by johndpope** [astropika/layerone_2019_ios#1]

**Comment by astropika** [comment]
Sorry, how do you mean?

The IP entered into the ip address entry modal will be written to UserDefaults (combined with http:// and /jpg_stream).

**Comment by johndpope** [comment]
This is a server running on network,right / is it like an ip camera? What code can I run to get it up? Seems jpegstream not so simple to get working on macOs/ I’m thinking a dockerfile with Linux backend.


 the screen with video playing looks really top shelf. I love it.
Was this designed by yourself?

**Comment by astropika** [comment]
This software was written to be used with the electronic badge for the layerone 2019 security conference in LA, https://www.layerone.org, the badge used this firmware https://github.com/m5stack/esp32-cam-demo and the accompanying hardware. But you should be able to use the app with any multipart/x-mixed-replace mjpeg stream.

The video is a looped 3 second clip from blade runner as that was the theme of the conference (2019 being the year the film was set in and LA being the location).

**Comment by johndpope** [comment]
thanks
